export const productosCono = [
	{
		id: 1,
		nombre: "Cono Sencillo",
		precio: 4000,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 0,
		crema: false,
		extras: [],
		imagen: "/helados/cono.webp",
	},
	{
		id: 2,
		nombre: "Cono Doble",
		precio: 6000,
		numSabores: 2,
		numSalsas: 1,
		numToppings: 0,
		crema: false,
		extras: [],
		imagen: "",
	},
	{
		id: 3,
		nombre: "Cono Relleno",
		precio: 6000,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 1,
		crema: false,
		extras: [],
		imagen: "",
	},
	{
		id: 4,
		nombre: "Cono Especial",
		precio: 11000,
		numSabores: 2,
		numSalsas: 1,
		numToppings: 2,
		crema: true,
		extras: [],
		imagen: "/helados/conoespecial.jpeg",
	},
	{
		id: 5,
		nombre: "Super Cono",
		precio: 9000,
		numSabores: 3,
		numSalsas: 1,
		numToppings: 0,
		crema: false,
		extras: [],
		imagen: "",
	},
	{
		id: 6,
		nombre: "Banana Split",
		precio: 12000,
		numSabores: 3,
		numSalsas: 1,
		numToppings: 1,
		crema: true,
		extras: ["banano"],
		imagen: "/helados/bananaSplit.webp",
	},
	{
		id: 7,
		nombre: "Copa Tropical",
		precio: 10000,
		numSabores: 2,
		numSalsas: 0,
		numToppings: 1,
		crema: true,
		extras: ["fruta"],
		imagen: "",
	},
	{
		id: 8,
		nombre: "Brownie con Helado",
		precio: 10000,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 1,
		crema: true,
		extras: ["brownie"],
		imagen: "/helados/BrownieConHelado.jpeg",
	},
	{
		id: 9,
		nombre: "Helado de la Casa",
		precio: 22000,
		numSabores: 4,
		numSalsas: 1,
		numToppings: 1,
		crema: false,
		extras: ["banano", "brownie", "fresa", "durazno", "barquillo"],
		imagen: "/helados/delaCasa.jpeg",
	}
];


export const productosCanasta = [
	{
		id: 1,
		nombre: "Mini Canasta",
		precio: 6000,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 1,
		crema: true,
		extras: [],
		imagen:"",
	},
	{
		id: 2,
		nombre: "Canasta Sencilla",
		precio: 10500,
		numSabores: 3,
		numSalsas: 1,
		numToppings: 0,
		crema: true,
		extras: [],
		imagen:"",
	},
	{
		id: 3,
		nombre: "Canasta Especial",
		precio: 12000,
		numSabores: 3,
		numSalsas: 1,
		numToppings: 2,
		crema: false,
		extras: [],
		imagen:"/helados/canastaEspecial.jpeg",
	}
];


export const productosVasos = [
	{
		id: 1,
		nombre: "Mini Vaso",
		precio: 4000,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 0,
		crema: false,
		extras: [],
		imagen:"",
	},
	{
		id: 2,
		nombre: "Vaso Sencillo",
		precio: 6000,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 1,
		crema: true,
		extras: [],
		imagen:"",
	},
	{
		id: 3,
		nombre: "Vaso Doble",
		precio: 8500,
		numSabores: 2,
		numSalsas: 1,
		numToppings: 2,
		crema: false,
		extras: [],
		imagen:"/helados/vasoDoble.png",
	},
	{
		id: 4,
		nombre: "Parfait",
		precio: 11000,
		numSabores: 2,
		numSalsas: 1,
		numToppings: 3,
		crema: true,
		extras: ["cereal"],
		imagen:"/helados/parfait.webp",
	},
	{
		id: 5,
		nombre: "Parfait de Yogurt Griego",
		precio: 11000,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 2,
		crema: false,
		extras: ["cereal", "yogurt griego"],
		imagen:"/helados/parfaitYogur.webp",
	}
];

export const productosWaffles = [
	{
		id: 1,
		nombre: "Waffle Frutos Rojos",
		precio: 15500,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 0,
		crema: true,
		extras: [],
		frutas: ["mora", "fresa"],
		imagen:"",
	},
	{
		id: 2,
		nombre: "Waffle Primavera",
		precio: 15500,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 0,
		crema: true,
		extras: ["arequipe"],
		frutas: ["banana", "fresa"],
		imagen:"/helados/wafletPrimavera.jpeg",
	},
	{
		id: 3,
		nombre: "Waffle Chocolate",
		precio: 15500,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 0,
		crema: true,
		extras: ["nutella", "brownie"],
		frutas: [],
		imagen:"/helados/wafletChocolate.jpeg",
	},
	{
		id: 4,
		nombre: "Waffle Tropical",
		precio: 16500,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 0,
		crema: true,
		extras: [],
		frutas: ["frutas mixtas"],
		imagen:"",
	},
	{
		id: 5,
		nombre: "Waffle a Tu Gusto",
		precio: 17500,
		numSabores: 1,
		numSalsas: 1,
		numToppings: 4,
		crema: true,
		extras: [],
		frutas: [],
		imagen:"",
	}
];


export const productosEnsaladas = [
	{
		id: 1,
		nombre: "Ensalada de Frutas Sencilla",
		precio: 11000,
		numSabores: 1,
		numSalsas: 0,
		numToppings: 0,
		crema: true,
		extras: ["frutas", "queso"],
		imagen:"/helados/ensaladaFrutas.webp",
	},
	{
		id: 2,
		nombre: "Ensalada de Frutas Grande",
		precio: 14000,
		numSabores: 3,
		numSalsas: 0,
		numToppings: 0,
		crema: true,
		extras: ["frutas", "queso"],
		imagen:"/helados/ensaladaGrande.jpeg",
	}
];
export const sabores = [
	{ id: 1, nombre: "Oreo" },
	{ id: 2, nombre: "Brownie" },
	{ id: 3, nombre: "Chocolate" },
	{ id: 4, nombre: "Arcoíris" },
	{ id: 5, nombre: "Frutos rojos" },
	{ id: 6, nombre: "Masmelo chicle" },
	{ id: 7, nombre: "Vainilla fresa" },
	{ id: 8, nombre: "Vainilla chips" },
	{ id: 9, nombre: "Tiramisú" },
	{ id: 10, nombre: "Ventiado de mora" }
];

export const toppings = [
	{ id: 1, nombre: "Moritas" },
	{ id: 2, nombre: "Almendras" },
	{ id: 3, nombre: "Maní" },
	{ id: 4, nombre: "Masmelo" },
	{ id: 5, nombre: "Chips de colores" },
	{ id: 6, nombre: "M&M" },
	{ id: 7, nombre: "Gusanitos" },
	{ id: 8, nombre: "Pepitas de colores" },
	{ id: 9, nombre: "Coco" },
	{ id: 10, nombre: "Lluvia de chocolate" },
	{ id: 11, nombre: "Oreo" },
	{ id: 12, nombre: "Explosiones de chicle" }
];

export const salsas = [
	{ id: 1, nombre: "Arequipe" },
	{ id: 2, nombre: "Leche condensada" },
	{ id: 3, nombre: "Chocolate" },
	{ id: 4, nombre: "Fresa" },
	{ id: 5, nombre: "Chicle" }
];

export const horario = [
	{ id: 1, dia: "Lunes", apertura: "4:00 PM", cierre: "10:00 PM", promo: false },
	{ id: 2, dia: "Martes", apertura: "4:00 PM", cierre: "10:00 PM", promo: false },
	{ id: 3, dia: "Miércoles", apertura: "4:00 PM", cierre: "10:00 PM", promo: "2x1" },
	{ id: 4, dia: "Jueves", apertura: "4:00 PM", cierre: "10:00 PM", promo: false },
	{ id: 5, dia: "Viernes", apertura: "4:00 PM", cierre: "10:00 PM", promo: false },
	{ id: 6, dia: "Sábado", apertura: "4:00 PM", cierre: "10:00 PM", promo: false },
	{ id: 7, dia: "Domingo", apertura: "4:00 PM", cierre: "10:00 PM", promo: false },
	{ id: 8, dia: "Lunes Festivo", apertura: "4:00 PM", cierre: "10:00 PM", promo: false }
];

export const categorias = [
	{ nombre: "Conos", productos: productosCono },
	{ nombre: "Canastas", productos: productosCanasta },
	{ nombre: "Vasos", productos: productosVasos },
	{ nombre: "Waffles", productos: productosWaffles },
	{ nombre: "Ensaladas", productos: productosEnsaladas },
];

export const preparacion = [
	{ nombre: "sabores", productos: sabores },
	{ nombre: "salsas", productos: salsas },
	{ nombre: "toppings", productos: toppings },
];